/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Returns the semver of the native addon.
 *
 * Used as a smoke test during Phase 0 to confirm the addon loads and
 * NAPI bindings work end-to-end on each platform.
 */
export declare function nativeVersion(): string
