/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Run a full ingest of `claude_dir`, writing into the SQLite file at
 * `db_path`. Returns a Promise that resolves to [`IngestStats`] or
 * rejects with a fatal error.
 *
 * Only `mode: "cold"` is implemented in Phase 1.
 *
 * The optional `on_progress` callback is invoked from the libuv
 * worker thread (threadsafe) with snapshots during ingest — start,
 * per-project-complete, and finalize. Throttled implicitly by the
 * coarse "per project" granularity.
 */
export declare function ingest(opts: IngestOptions, onProgress?: (progress: IngestProgress) => void): Promise<IngestStats>

export interface IngestError {
  slug: string
  message: string
}

/**
 * Options for [`ingest`].
 *
 * Mirrors the RFC 003 `IngestOptions` TypeScript shape. Fields that RFC
 * marks optional are `Option<T>` here and get defaulted in
 * [`IngestOptions::resolved`].
 */
export interface IngestOptions {
  claudeDir: string
  dbPath: string
  /**
   * `"cold"` is the only value supported in Phase 1. `"warm"` lands in
   * Phase 3 and currently errors.
   */
  mode: string
  progressIntervalMs?: number
  parallelism?: number
}

/**
 * Progress snapshot for the optional on-progress callback. Fires once
 * on start (`phase = "scanning"`, projects_total set), once per project
 * completion (`phase = "parsing"`), and once at finalization
 * (`phase = "finalizing"`). The JS side can subscribe to drive a
 * progress bar / TUI status line without having to poll.
 */
export interface IngestProgress {
  phase: string
  projectsDone: number
  projectsTotal: number
  elapsedMs: number
}

/**
 * Stats returned on successful ingest.
 *
 * Mirrors the RFC 003 `IngestStats` shape. Errors accumulated during
 * ingest (e.g. bad JSONL lines) are returned in `errors`; fatal errors
 * reject the promise instead.
 */
export interface IngestStats {
  durationMs: number
  projectsProcessed: number
  sessionsProcessed: number
  messagesWritten: number
  subagentsWritten: number
  /**
   * Non-fatal errors collected during ingest — parse failures, missing
   * session files, etc.
   */
  errors: Array<IngestError>
}

/** Returns the semver of the native addon. */
export declare function nativeVersion(): string
